//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaziciEmlak.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAdmin
    {
        public int AdminID { get; set; }
        public string Admin { get; set; }
        public string Sifre { get; set; }
    }
}
